# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Lab1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Lab1/Lab1.sln
    - name: Build
      run: dotnet build ./Lab1/Lab1.sln --no-restore
    - name: Test
      run: dotnet test ./Lab1/Lab1.Test/Lab1.Test.csproj --no-build --verbosity normal
